### ISSUE TITLE
Flywheel User Account - Tingyu Wang

### ISSUE THREAD

**Issue by flittera** [kids-first/devops-requests#12]
Please describe needed access to the best of your ability:
Full name: Tingyu Wang
Google Email: troywty@gmail.com
Institution: University of Pennsylvania
Position: Research Assistant
StudyName(CBTN ID preffered): Medullo cohort (duplicate copy project)
Purpose of the access: UPenn team member needs to access Flywheel images for research purposes as part of the ongoing collaboration between CBTN the the radiation oncology department at UPenn
Notes:

PLEASE NOTE THIS TICKET REQUIRES APPROVAL

**Comment by allisonheath** [comment]
Approved

**Comment by alubneuski** [comment]
User is created.
