### ISSUE TITLE
Flywheel Access: Jo Lynne Rokita

### ISSUE THREAD

**Issue by jharenza** [kids-first/devops-requests#15]
Please describe needed access to the best of your ability:
Full name: Jo Lynne Rokita
Google Email: jolynnerokita@d3b.center
Institution: CHOP
Position: Supervisory Bioinformatics Scientist
StudyName(CBTN ID preffered): sd-bhjxbdqk, sd-m3dbxd12, sd-8y99qzjj
Purpose of the access:
Notes:

PLEASE NOTE THIS TICKET REQUIRES APPROVAL

**Comment by allisonheath** [comment]
Approved 👍

**Comment by blackdenc** [comment]
Added
