### ISSUE TITLE
[general-devops] Automation that would allow us to take snapshots of our ES cluster in QA

### ISSUE THREAD

**Issue by evans-g-crsj** [kids-first/devops-requests#20]
Currently, there is no way to easily fetch data locally from our ES cluster (QA).

Having a local copy of that data would allow devs to make much more testing when developing. 

Therefore, having the possibility 1) to execute a script that take a snapshot of the cluster and dump it in S3 2) to have the permission to access the snapshot in S3

Note: I verified with Jeremy that there is no sensible data in QA.

**Comment by blackdenc** [comment]
Snapshot saved to `kf-strides-es-snapshot-bucket`
