### ISSUE TITLE
New Flywheel user account - Sherjeel Arif

### ISSUE THREAD

**Issue by afamiliar** [kids-first/devops-requests#22]
Please describe needed access to the best of your ability:
First name: Sherjeel
Last name: Arif
Google Email: sherjeelarif@gmail.com
Institution: Penn Medicine
Position: Image Analyst
StudyName(CBTN ID preffered):  LGG
Purpose of the access: To process data for ongoing Penn collaboration
Notes:

PLEASE NOTE THIS TICKET REQUIRES APPROVAL

**Comment by afamiliar** [comment]
approved

**Comment by blackdenc** [comment]
User added to Flywheel
