### ISSUE TITLE
CBTN_D0130 Flywheel Access 

### ISSUE THREAD

**Issue by kamnaacool** [kids-first/devops-requests#24]
Please describe needed access to the best of your ability:
First name: Rohan 
Last name: Bareja
Google Email: rohan1925@gmail.com
Institution: Case Western Reserve University
Position: Project Lead
StudyName(CBTN ID preffered): CBTN_D0130
Purpose of the access: Beta testers 
Notes: Requires "Read-Only" access to the LGG, HGG and Medullo cohorts 

First name: Pallavi
Last name: Tiwari
Google Email: pallavi.tiwar@gmail.com
Institution: Case Western Reserve University
Position: Primary Investigator
StudyName(CBTN ID preffered): CBTN_D0130
Purpose of the access: Beta testers 
Notes: Requires "Read-Only" access to the LGG, HGG and Medullo cohorts 
PLEASE NOTE THIS TICKET REQUIRES APPROVAL

**Comment by afamiliar** [comment]
approved

**Comment by blackdenc** [comment]
Users added to Flywheel
