### ISSUE TITLE
CBTTC_0033 - Flywheel Access for Dr. Kristina Cole

### ISSUE THREAD

**Issue by eappert** [kids-first/devops-requests#25]
Please describe needed access to the best of your ability:
First name:  Kristina
Last name:  Cole
Google Email: krisatsaves@gmail.com
Institution: Children's Hospital of Philadelphia
Position: Attending Physician, Oncology
StudyName(CBTN ID preffered):  CBTTC_0033
Purpose of the access: Dr. Cole would like to view/analyze the MRI images for a cohort of subjects for which she got samples for her CBTN approved project. 
Notes:

PLEASE NOTE THIS TICKET REQUIRES APPROVAL

**Comment by afamiliar** [comment]
approved

**Comment by blackdenc** [comment]
User added to Flywheel
