### ISSUE TITLE
CBTTC_0033 - Flywheel access for Derek Oldridge

### ISSUE THREAD

**Issue by eappert** [kids-first/devops-requests#26]
Please describe needed access to the best of your ability:
First name: Derek
Last name:  Oldridge
Google Email: derek.oldridge@gmail.com
Institution: Children's Hospital of Philadelphia
Position: Lab Medicine Fellow
StudyName(CBTN ID preffered):  CBTTC_0033
Purpose of the access: Derek is on Dr. Cole's team for her approved project CBTTC_0033. They need to be able to view/analyze the images for a cohort of subjects for which they received samples. 
Notes:

PLEASE NOTE THIS TICKET REQUIRES APPROVAL

**Comment by afamiliar** [comment]
approved

**Comment by blackdenc** [comment]
User added to Flywheel
