### ISSUE TITLE
New Flywheel Account - Giulia Fadda

### ISSUE THREAD

**Issue by afamiliar** [kids-first/devops-requests#29]
Please describe needed access to the best of your ability:
First name: Giulia
Last name: Fadda
Google Email: g.fadda16@gmail.com
Institution: McGill
Position: Physician
StudyName(CBTN ID preffered):  
Purpose of the access: Collaborator (Brenda Banwell's team)
Notes:

PLEASE NOTE THIS TICKET REQUIRES APPROVAL

**Comment by afamiliar** [comment]
approved

**Comment by blackdenc** [comment]
User added to Flywheel
