### ISSUE TITLE
New Flywheel User - Mariam Aboian

### ISSUE THREAD

**Issue by velascor** [kids-first/devops-requests#32]
Please describe needed access to the best of your ability:
First name: Mariam
Last name: Aboian
Google Email: mariam.aboian@gmail.com
Institution: Yale University
Position: Assistant Professor and PNOC/CBTN Imaging Working Group Member
StudyName(CBTN ID preffered): HGG
Purpose of the access: Per request: " Our group focuses on characterizing the imaging features within pediatric brain tumors that predict tumor molecular subgroups and patient outcomes. The goal of our project is to develop imaging based classification of pediatric high grade gliomas that will stimulate discovery of novel imaging biomarkers that predict driver mutations in these tumors. "
Notes: n/a

PLEASE NOTE THIS TICKET REQUIRES APPROVAL

**Comment by afamiliar** [comment]
Request is on hold - all accounts for external users (existing & new requests) are currently on hold until all data is re-processed with updated de-identification pipeline.

**Comment by afamiliar** [comment]
Flywheel user created & added to "HGG_nifti" project
