### ISSUE TITLE
New Flywheel Access - Dr. Sadhana Jackson, CBTTC_0060

### ISSUE THREAD

**Issue by eappert** [kids-first/devops-requests#33]
Please describe needed access to the best of your ability:
First name: Sadhana
Last name: Jackson
Google Email: sadhanavivens@gmail.com
Institution: NIH
Position: Pediatric Neuro-oncologist, Head - Developmental Therapeutics and Pharmacology.
StudyName(CBTN ID preffered):  CBTTC_0060
Purpose of the access: Dr. Sadhana Jackson would like to have access to high grade glioma MRIs for her study. 
Notes:

PLEASE NOTE THIS TICKET REQUIRES APPROVAL

**Comment by eappert** [comment]
@afamiliar @allisonheath @alubneuski @blackdenc - do you have an update on this ticket?

sorry for tagging everyone - not sure who that question should be directed to. Thanks!

**Comment by afamiliar** [comment]
@eappert hi! we have paused granting Flywheel access to new users - we are re-processing all of the data and expect to be up and running again in a few weeks

**Comment by eappert** [comment]
Thanks @afamiliar!  Please let me know when these resume so I can keep the investigator updated.

**Comment by eappert** [comment]
Hi @afamiliar! just wanted to check in and see if there are any updates? Thanks

**Comment by afamiliar** [comment]
Flywheel user account created & user added to "HGG_nifti" project
