### ISSUE TITLE
New Flywheel Access - Keshwyn Annauth & Patrick Hales (CBTTC_D0110)

### ISSUE THREAD

**Issue by HigginsD3b** [kids-first/devops-requests#34]
Please describe needed access to the best of your ability: Looking for imaging access via Flywheel for training machine-learning algorithms in tumor identification and discovery.

**2 Users:**
First name: Keshwyn
Last name: Annauth
Google Email: keshwyn.annauth@gmail.com
Position: Postdoctoral Researcher

First name: Patrick
Last name: Hales
Google Email: phales80@gmail.com
Position: Principle Investigator

Institution: University College London
StudyName(CBTN ID preffered): CBTTC_D0110
Purpose of the access: (from their CBTN abstract)

> We intend to develop a set of tools which will use artificial intelligence (AI) to aid with the clinical management of pediatric brain tumors. These tools will automatically detect brain tumors in MRI scans, and provide predictions as to what subtype of tumor the patient has. We will also use AI to help detect early signs of disease progression.

Notes:

PLEASE NOTE THIS TICKET REQUIRES APPROVAL

**Comment by afamiliar** [comment]
Request is on hold - all accounts for external users (existing & new requests) are currently on hold until all data is re-processed with updated de-identification pipeline.

**Comment by afamiliar** [comment]
Awaiting response from researchers as to which disease cohorts or C-IDs they would like access to

**Comment by HigginsD3b** [comment]
I heard a response from Keshwyn, explaining they are interested in general access to the imaging data.

> I’m still very much interested in getting access to the imaging data. My current research is still in the initial stages and I’m exploring a range of paediatric brain tumours, so access to any/all cohorts for paediatric brain tumours would be ideal.

**Comment by afamiliar** [comment]
Users created. Added to available CBTN cohorts (DIPG, high-grade glioma, and medulloblastoma). Will add to additional cohorts (low-grade glioma, ATRT, DMG, HTAN)

**Comment by afamiliar** [comment]
Users added to LGG and ATRT. DMG/HTAN project still under review

**Comment by HigginsD3b** [comment]
Sent an introductory email to Keshwyn, with directions for how to access the data through Flywheel.
