### ISSUE TITLE
Flywheel account - Neurosurgery residents

### ISSUE THREAD

**Issue by afamiliar** [kids-first/devops-requests#37]
Please describe needed access to the best of your ability:
First name: NA
Last name: NA
Google Email: chopneurosurgeryresidents@gmail.com
Institution: CHOP
Position: Neurosurgery Residents
StudyName(CBTN ID preffered): 
Purpose of the access: to work on tumor segmentations
Notes:

PLEASE NOTE THIS TICKET REQUIRES APPROVAL

**Comment by afamiliar** [comment]
user account created

**Comment by blackdenc** [comment]
Users are
```
Michael Spadola, Elias Atallah, Erin Graves
```
May consider separating into separate user accounts later on
