### ISSUE TITLE
CBTN_D0143 LGG Project

### ISSUE THREAD

**Issue by kamnaacool** [kids-first/devops-requests#38]
Please describe needed access to the best of your ability:
First name: Sabine
Last name: Mueller
Google Email: Bine343@gmail.com
Institution: UCSF
Position: SC Member
StudyName(CBTN ID preffered): CBTN_D0143
Purpose of the access: The main objective of this project is to assess if the CBTN data can be used to perform a synthetic trial mimicking a prospective clinical trial that was conducted via PNOC (PNOC001). 
In order to perform this project,  we like to collect data and imaging on all patients with recurrent LGG who were treated with everolimus that are part of the CBTN cohort. Images will undergo central imaging review and assess for clinical outcome with the same endpoints used for the actual clinical trial
Notes: There are Additional users listed below
Michael Prados, Michael.prados@gmail.com
Benjamin H Kann, bhkann@gmail.com
Kevin X Liu, kxliu19@gmail.com
Rifaquat Rahman, Rifaquat.rahman@gmail.com

PLEASE NOTE THIS TICKET REQUIRES APPROVAL

**Comment by kamnaacool** [comment]
Adding the subject List here 
Please let me know for non-CHOP subjects so we can reach out to the sites and obtain the images.
[CBTN_D0143_Imaging Request.xlsx](https://github.com/kids-first/devops-requests/files/6599362/CBTN_D0143_Imaging.Request.xlsx)

**Comment by afamiliar** [comment]
- The following user accounts were created: Sabine Mueller, Michael Prados, Kevin X Liu, Rifaquat Rahman
     > Benjamin H Kann user already exists
- "CBTN_D0143" project created on Flywheel
- users added to "CBTN_D0143" project
- data for 16 subjects in provided Excel sheet added to project

**Waiting on guidance from clinical research team as to the remaining 44 subjects**, and potential additional time points for above 16.

**Comment by afamiliar** [comment]
CHOP data complete
