### ISSUE TITLE
Alessandra Rigamonti Request for New Flywheel Access for LGG Liquid Biopsy

### ISSUE THREAD

**Issue by AlessandraRig** [kids-first/devops-requests#39]
Please describe needed access to the best of your ability:
First name: Alessandra
Last name:  Rigamonti
Google Email: asr255@cornell.edu
Institution: CHOP/ Drexel University School of Medicine
Position: Summer Student / 2nd year Medical Student
StudyName(CBTN ID preffered): LGG Liquid Biopsy
Purpose of the access: Summer Research work
Notes:

PLEASE NOTE THIS TICKET REQUIRES APPROVAL

**Comment by afamiliar** [comment]
account created & added to liquid biopsy project
