### ISSUE TITLE
Thinh "Bin" Nguyen New FlyWheel Access (CBTN CRU team member)

### ISSUE THREAD

**Issue by robinssm** [kids-first/devops-requests#40]
Please describe needed access to the best of your ability:
First name: Thinh
Last name: Nguyen
Google Email: bin@d3b.center
Institution: CHOP - D3b CRU team
Position: CRA for CBTN/Liquid Biopsy
StudyName (CBTN ID prefered): Need access to all D3b projects
Purpose of the access: Bin will be pulling all accession numbers for CHOP subjects. Needs access to existing projects to see what's already been pulled
Notes: Can match Shannon Robins level of access

PLEASE NOTE THIS TICKET REQUIRES APPROVAL

**Comment by afamiliar** [comment]
User created & added to D3b projects
