### ISSUE TITLE
New Flywheel accounts for Seven Bridges team (2)

### ISSUE THREAD

**Issue by RUPPG** [kids-first/devops-requests#43]
Please describe needed access to the best of your ability:
First name: Milica
Last name: Miletic
Google Email: milica.miletic@sbgenomics.com
Institution:Seven Bridges Genomics
Purpose of the access: INCLUDE imaging pilot

First name: Bojan
Last name: Stankic
Google Email: bojan.stankic@sbgenomics.com
Institution:Seven Bridges Genomics
Purpose of the access: INCLUDE imaging pilot

First name: Boris
Last name: Pejic
Google Email: boris.pejic@sbgenomics.com
Institution:Seven Bridges Genomics
Purpose of the access: INCLUDE imaging pilot

First name: Zorana
Last name: Mitrovic
Google Email: zorana.mitrovic@sbgenomics.com
Institution:Seven Bridges Genomics
Purpose of the access: INCLUDE imaging pilot

**Comment by afamiliar** [comment]
Approved, created, & added to TCIA-CPTAC-BGM project
