### ISSUE TITLE
CBTN_D0149 Haj-Hosseini

### ISSUE THREAD

**Issue by kamnaacool** [kids-first/devops-requests#44]
Please describe needed access to the best of your ability:
First name: Neda 
Last name: Haj-Hosseini
Google Email (associated with your Flywheel account): 
Projects to grant access to: Listing in order of priority- **LGG (incl. Oligodendrogliomas and Astrocytomas) , Medulloblastoma, Ependymoma,**  ATRT, Glanglioma, Cranios, Choroid Plexus Tumors, Meningioma, Brainstem Gliomas: DIPG
Level of access [Read-Only, Read-Write, Admin]: 
Reason for access: Received via Data Access Request 
[clinicalDataFileRepo_20210713.xlsx](https://github.com/kids-first/devops-requests/files/6833889/clinicalDataFileRepo_20210713.xlsx)

PLEASE NOTE THIS TICKET REQUIRES APPROVAL

**Comment by afamiliar** [comment]
Please add Gmail to use for Flywheel account

**Comment by kamnaacool** [comment]
neda.hh.580@gmail.com
tampuiulianemil@gmail.com

**Comment by afamiliar** [comment]
user accounts created & added to current CBTN projects: ATRT, DIPG, HGG, LGG, Medullo

DMG.HTAN and additional histologies to be available soon
