### ISSUE TITLE
Flywheel access for Avi Kelman

### ISSUE THREAD

**Issue by fiendish** [kids-first/devops-requests#45]
First name: Avital
Last name: Kelman
Google Email: avikelman@d3b.center
Institution: D3b
StudyName(CBTN ID preffered): all of them?
Purpose of the access: test uploading lots of images to flywheel

PLEASE NOTE THIS TICKET REQUIRES APPROVAL

**Comment by afamiliar** [comment]
New user created, added to available CBTN projects & new "pathology_testing" project
