### ISSUE TITLE
CBTN_D0148

### ISSUE THREAD

**Issue by kamnaacool** [kids-first/devops-requests#47]
Please describe needed access to the best of your ability:
First name: Marianne 
Last name: Aznar
Google Email:
Institution: University of Manchester
Position: Senior Lecturer 
StudyName(CBTN ID preffered): CBTN_D0148
Purpose of the access: To view images along with the clinical data 
Notes: Histologies of interest: Brainstem Glioma-DIPG 
Brainstem Glioma-NOS
Brainstem Glioma-tectal 
Ganglioma
Glial-neuronal tumor NOS
HGG/astrocytoma(WHO grade III/IV)
LGG/astrocytoma(WHO grade I/II)
Oligo
SEGA 

PLEASE NOTE THIS TICKET REQUIRES APPROVAL

**Comment by afamiliar** [comment]
Please add Gmail to use for Flywheel account

**Comment by kamnaacool** [comment]
marianneaznar@gmail.com

**Comment by afamiliar** [comment]
user accounts created & added to current CBTN projects: ATRT, DIPG, HGG, LGG, Medullo

DMG.HTAN and additional histologies to be available soon
