### ISSUE TITLE
New Flywheel Access - Anna Maria Buccoliero (CBTTC_D0092)

### ISSUE THREAD

**Issue by Bin1602** [kids-first/devops-requests#48]
Please describe needed access to the best of your ability: Dr. Buccoliero is working on an angiocentric gliomas cohort (CBTN_D0092) and needs access to MRI images of subject C116112 to determine the exact location of the tumor as pathology report and MRI written reports aren't specific enough.

First name: Anna Maria
Last name: Buccoliero
Google Email: ambuccoliero1967@gmail.com
Institution: Meyer Hospital Florence Italy  
Position: Director Pathology 
StudyName(CBTN ID preffered): CBTTC_D0092
Purpose of the access: Dr. Buccoliero needs access to MRI sessions of subject C116112 to determine if the location of tumor as written reports aren't specific enough.

Notes: Please contact Jennifer Mason (masonjl@chop.edu) or Thinh Nguyen (nguyentq@chop.edu) if there are any questions.

PLEASE NOTE THIS TICKET REQUIRES APPROVAL

**Comment by afamiliar** [comment]
@Bin1602 this subject (C116112 / 7316-480) doesn't exist on Flywheel. If desired, a data request will need to be submitted to Radiology. Please comment with how to proceed.

**Comment by Bin1602** [comment]
@afamiliar I already submitted 6 accession numbers of this subject on Friday last week to radiology. The request # is 1491 and I also sent you the naming manifest on that same day. We also discussed that these 6 MRI sessions will go into a new D3b/DNET folder (since we do not have this diagnosis on Flywheel yet).

**Comment by afamiliar** [comment]
@Bin1602 ok, great! Thanks for the info.

approved. @blackdenc please add new user, group: CBTTC_D0092 as admin, project: DNET as read-only (r)

**Comment by afamiliar** [comment]
Data uploaded to DNET on Flywheel. Awaiting user creation by @blackdenc

**Comment by Bin1602** [comment]
@blackdenc Hi! Can you give me an update on Anna Maria's flywheel account?

**Comment by blackdenc** [comment]
Hi @Bin1602 , sorry I'm a little behind on these requests. I have added the new account and added her to the DNET project as a read-only user, but I can't see the `CBTTC_D0092` group.

**Comment by Bin1602** [comment]
@blackdenc Thank you so much! And Dr. Buccoliero only needs to see MRI images of subject C116112 (which is the DNET project), so we are good here. Thanks again for your help!

**Comment by blackdenc** [comment]
Glad to hear! Closing this ticket
