### ISSUE TITLE
Flywheel User Account - Benjamin Kann

### ISSUE THREAD

**Issue by flittera** [kids-first/devops-requests#5]
Please describe needed access to the best of your ability: Need to create a Flywheel user account for a PI at Boston Children's Hospital.
Full name: Benjamin Kann
Google Email: bhkann@gmail.com
Institution: Boston Children's Hospital
Position: Physician
StudyName(CBTN ID preffered): HGG, LGG (duplicate copy projects)
Purpose of the access: PI needs to access Flywheel images for research purposes
Notes:

PLEASE NOTE THIS TICKET REQUIRES APPROVAL

**Comment by blackdenc** [comment]
User has been added
