### ISSUE TITLE
CBTN_D0154: Wang

### ISSUE THREAD

**Issue by kamnaacool** [kids-first/devops-requests#50]
Please describe needed access to the best of your ability:
First name: Yanran Joyce
Last name: Wang
Google Email: wangyanran100@gmail.com
Institution: Stanford University
Position: Postdoc Research fellow
StudyName(CBTN ID preffered): CBTN_D0154
Purpose of the access: View images as a part of the project (Title: Predicting distant metastasis and chemotherapy benefit in pediatric brain cancer)
Notes: The cohort of interest is Medulloblastoma

PLEASE NOTE THIS TICKET REQUIRES APPROVAL

**Comment by afamiliar** [comment]
Approved. @blackdenc please add new user to `CBTN_D0154` group, `Medullo` project

**Comment by afamiliar** [comment]
User account created, added to `CBTN_D0154` group, `Medullo` project
