### ISSUE TITLE
New Flywheel Access - Benjamin Kann (CBTN_D0122)

### ISSUE THREAD

**Issue by HigginsD3b** [kids-first/devops-requests#54]
Please describe needed access to the best of your ability:
First name: Benjamin
Last name: Kann
Google Email: bhkann@gmail.com
Institution: Boston Children's Hospital/Brigham and Women'sHospital/Dana-Farber Cancer Institute, HarvardMedical School
Position: Instructor, Radiation Oncology
StudyName(CBTN ID preffered): CBTN_D0122
Purpose of the access: As described in [their proposal](https://d3b.atlassian.net/browse/CBTN-89)...

> We will develop non-invasive, imaging-based signatures to predict underlying BRAF-alterations and molecular subtype.

Notes: This group needs access to LGG images.

PLEASE NOTE THIS TICKET REQUIRES APPROVAL

**Comment by afamiliar** [comment]
@HigginsD3b Ben Kann has previously been granted access to Flywheel & the LGG dataset ([https://github.com/kids-first/devops-requests/issues/5]). Is there anything else we need to provide (e.g., data, additional user accounts)?

**Comment by HigginsD3b** [comment]
Perfect! I think we can close this one then. 

Sorry for the confusion, thanks for your help!
