### ISSUE TITLE
Imaging Request - Rauschecker (CBTN_D0152)

### ISSUE THREAD

**Issue by HigginsD3b** [kids-first/devops-requests#55]
Please describe needed access to the best of your ability:

First name: Andreas
Last name: Rauscheker
Google Email: `andreas.rauschecker@gmail.com `

Collaborator Emails: Andreas has a collaborator who also needs access. According to him, `pierre.nedelec@ucsf.edu` "should work." If not, use `pfl.nedelec@gmail.com`

Institution: UCSF
Position: Assistant Professor
Study Name(CBTN ID preffered): CBTN_D0152
Purpose of the access: 

> -To fine-tune a 3D segmentation network that operates at the level of inter-human variability on pediatric low-grade gliomas
> -To automate volumetric assessment of pediatric low-grade gliomas based on a single MRI sequence (FLAIR or T2)
> -To optimize a previously published imaging pipeline for specifically characterizing pediatric low-grade gliomas via human-interpretable imaging features in order to correlate these with tumoral genetics and/or clinical outcome measures

Notes: Needs access to the LGG dataset.

PLEASE NOTE THIS TICKET REQUIRES APPROVAL

**Comment by afamiliar** [comment]
Approved. @blackdenc please add the 2 new users to (new) `CBTN_D0152` group, `LGG` project

**Comment by HigginsD3b** [comment]
Comment from @blackdenc: 

> I added their accounts, and I added them to the right group, but there’s not a good way to add the project to that group. I’m working with Ariana on it now, but they should be able to login in the meantime.

**Comment by afamiliar** [comment]
Users added to `LGG` project
