### ISSUE TITLE
New Flywheel User - Tej Verma (student under Mariam Aboian)

### ISSUE THREAD

**Issue by velascor** [kids-first/devops-requests#57]
Please describe needed access to the best of your ability:
First name: Tej 
Last name: Verma
Google Email:  tejverma@gmail.com
Institution: NYU
Position: Student
StudyName(CBTN ID preferred): LGG project associated with Dr. Mariam Aboian
Purpose of the access: helping Dr. Aboian with the LGG project
Notes: Associated with project CBTN_D0143

PLEASE NOTE THIS TICKET REQUIRES APPROVAL

**Comment by afamiliar** [comment]
Approved. @blackdenc please add new user to `CBTN_D0143` group, `CBTN_D0143` project

**Comment by afamiliar** [comment]
Confirmed user was added to `CBTN_D0143` project
