### ISSUE TITLE
New Flywheel User - Gabe Cassinelli Petersen (student under Mariam Aboian)

### ISSUE THREAD

**Issue by velascor** [kids-first/devops-requests#58]
Please describe needed access to the best of your ability:
First name: Gabe 
Last name: Cassinelli Petersen
Google Email: gabriel.cassinellipetersen@gmail.com
Institution: Yale
Position: Student
StudyName(CBTN ID preffered): HGG_nifti
Purpose of the access: helping Dr. Aboian with her HGG project
Notes: associated with this request: https://github.com/kids-first/devops-requests/issues/32 

PLEASE NOTE THIS TICKET REQUIRES APPROVAL

**Comment by velascor** [comment]
hi @afamiliar - I wanted to check in to see what the timeline is for this? Thanks!

**Comment by afamiliar** [comment]
User account created, added to `CBTN_D0143` project
