### ISSUE TITLE
Flywheel access request - Jeffrey Ware

### ISSUE THREAD

**Issue by afamiliar** [kids-first/devops-requests#6]
Please describe needed access to the best of your ability:
Full name: Jeff Ware
Google Email: jbwaresyr@gmail.com
Institution: Hospital of the University of Pennsylvania
Position: radiologist
StudyName(CBTN ID preffered): LGG, liquid bioposy
Purpose of the access: Penn collaborator
Notes:

PLEASE NOTE THIS TICKET REQUIRES APPROVAL

**Comment by allisonheath** [comment]
👍 approved

**Comment by blackdenc** [comment]
User has been added to CHOP Flywheel instance
